### ISSUE TITLE
Simple server_process test

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/datasheet-server#13]
The Travis build should start a simple server, and confirm that basic routes work. See [this test](https://github.com/forensic-architecture/timemap/blob/develop/test/server_process.js) in timemap as a reference.

Setting this up here is a touch more involved, as the server currently needs a connection with a google sheet to be of any use; which in turn requires a service account private key and email that is authenticated on the sheet from which it is pulling data.

Two solutions I can think of here:
 1. explore Travis private variables, and set the build up with a private key and email to test.
 2. Is there a way to access a public sheet through the [sheets API](https://developers.google.com/sheets/api/) without a service account? In this case we could test on a public sheet.
 3. Create a dummy config with no sheets, to bypass this connection, and very simply test whether the server builds and runs.

The easiest step forward is number 3, I think.

**Comment by jlieb10** [comment]
@breezykermo I have the tests passing with environmental variables but it's still a work in progress because I'm encrypting the `.env` file. Using Travis' built in vars wasn't working for a multiline value (escaped, quoted, or otherwise). This is not an ideal open source solution bc it would require everyone to have their own Travis config. 

How are the env vars--particularly the private key--getting set in production (assuming this is being used in production somewhere)?

diff is here: https://github.com/forensic-architecture/datasheet-server/compare/develop...jlieb10:develop
tests are here: https://travis-ci.org/jlieb10/datasheet-server/jobs/462922869

**Comment by jlieb10** [comment]
Gotcha. I think `.env` variables are generally the way to go for this sort of thing, but there's not a lot that can be done to get an entire key to properly work as an env var besides SSHing into the server, as you say, or encrypting the file.

I've read the docs for the Google Sheets API and it seems like we have the options of: 
1. running the server on their platform so they handle the authorization, which might be a production solution at some point but isn't a testing or open source solution
2. using JWT-- the current solution/problem
3. using OAuth-- which would require 'users' to grant permission to the app. I think this could be automated (maybe even headless) if one saves valid dummy google credentials as env vars.

I think trying OAuth would be my next step-- what do you think?

**Comment by breezykermo** [comment]
Thinking more about this, I think that OAuth is the wrong direction. It could work, but it adds a fair amount of complexity for a fairly simple thing that we're trying to do: get an instance running to test in Travis.

I think what we actually want is a [Travis encrypted variable](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml). We shouldn't have to change any files but the .travis.yml, I would have thought, as this is a problem confined to Travis, rather than being an issue with the server configuration more generally. I have to imagine that there's a solution to encrypt the private key with escape characters, but I haven't used Travis in this way before.

**Comment by jlieb10** [comment]
The string is too long to be a Travis encrypted variable so it gets rejected if you try that which is why I went for the encrypted file. I am playing with base64 encoding the string now.

**Comment by jlieb10** [comment]
`data too large - consider using travis encrypt-file or travis env set` is the error thrown for your reference.

Reading around online, it seems that Travis used to support JWT but has intentionally stopped supporting it because of concerns about securely handing a private key.

**Comment by jlieb10** [comment]
went with adding a precommit commit hook to encrypt `.env` file and re-add the result to git -- seems to be working but someone listed as an FA contributor will need to create and commit with an `.env` file then push the `.env.enc` result for travis to pass

https://github.com/forensic-architecture/datasheet-server/pull/24
