### ISSUE TITLE
Create Google Sheet with relevant information from Ayotzinapa case

### ISSUE THREAD

**Issue by jlieb10** [forensic-architecture/datasheet-server#15]
Glean and restructure data from Ayotzinapa case in order to have richer sample information to further develop Timemap (as well as Datasheet Server).

http://www.plataforma-ayotzinapa.org/static/archive/data/data.json

**Comment by jlieb10** [comment]
Started here: https://docs.google.com/spreadsheets/d/15gb_aYJw7WSVZmtS0FZvcpGx1-kwKX3VHH8YV6La4hY/edit?usp=sharing but sheet is not getting pulled in as expected so reading through the source

**Comment by breezykermo** [comment]
Thanks for this! Would you be able to post the Datasheet and Timemap config.js that you used to get this sheet working in development?

**Comment by breezykermo** [comment]
@jlieb10 closing this as the document seems to have been deleted. Feel free to open a new issue if it's still active!
