### ISSUE TITLE
No datasheet example

### ISSUE THREAD

**Issue by jpdh9881** [forensic-architecture/datasheet-server#83]
Environment
-----------
n/a

Steps to reproduce (for bugs only)
-----------------------------
n/a

Current Behavior
----------------
I can't find an example of a datasheet that would be compatible with this app.

Expected Behavior
-----------------
A link to an example datasheet or a document that outlines how a datasheet should be formatted (columns, rows, etc.).
There are links to an example datasheet [here](https://github.com/forensic-architecture/timemap/wiki/running-timemap-and-datasheet-server-locally) but the link seems to be dead.

**Comment by breezykermo** [comment]
Hi there- the docs are out of date, apologies. There is an example datasheet locally in the repo `data` folder: [here is the link](https://github.com/forensic-architecture/datasheet-server/blob/main/data/timemap_data.xlsx).

**Comment by jpdh9881** [comment]
Thank you! Looking forward to checking this out
